app: agion

web:
  image: registry.digitalocean.com/breezy-container-registry-repo/agion/web:latest
  imagePullPolicy: IfNotPresent
  service:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 6
    AverageValue: 50
  resources:
      limits:
        cpu: "0.5"
        memory: 500Mi
      requests:
        cpu: "0.05"
        memory: 50Mi 
  ingress:
  - name: agion
    host: agion.new-brz.net
    path: /
    pathType: Prefix
    # tlssecret:  breezy-tls
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: 8m
      nginx.ingress.kubernetes.io/proxy-buffering: "on"
      nginx.ingress.kubernetes.io/server-snippet: |
        gzip on;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
  - name: agion-proxied
    host: breezyagion.cms4profit.com
    path: /
    pathType: Prefix
    # tlssecret:  breezy-tls
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: 8m
      nginx.ingress.kubernetes.io/proxy-buffering: "on"
      nginx.ingress.kubernetes.io/server-snippet: |
        gzip on;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;




fpm:
  image: registry.digitalocean.com/breezy-container-registry-repo/agion/fpm:latest
  imagePullPolicy: IfNotPresent
  service:
    - name: fpm
      protocol: TCP
      port: 9000
      targetPort: 9000
  metrics:
    - name: metrics
      protocol: TCP
      port: 80
      targetPort: 9253
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 6
    AverageValue: 50
  resources:
      limits:
        cpu: "0.5"
        memory: 500Mi
      requests:
        cpu: "0.05"
        memory: 50Mi 

cron:
  image: registry.digitalocean.com/breezy-container-registry-repo/agion/cron:latest
  imagePullPolicy: IfNotPresent
  resources:
      limits:
        cpu: "0.5"
        memory: 500Mi
      requests:
        cpu: "0.3"
        memory: 500Mi 
  restartPolicy: OnFailure
  backoffLimit: 3
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  parallelism: 1
  concurrencyPolicy: Forbid
  nodeAffinity:
    enabled: true
    nodeSelectors:
      - key: app
        operator: In
        values:
          - mixed
  cronjobs:
    # Sending
    - name: start-sending-ua
      schedule: "*/15 * * * *"
      args: ["php", "/opt/apps/laravel/artisan", "start:sending", "ua"]
    - name: start-sending-by
      schedule: "*/15 * * * *"
      args: ["php", "/opt/apps/laravel/artisan", "start:sending", "by"]
    - name: start-sending-kz
      schedule: "*/15 * * * *"
      args: ["php", "/opt/apps/laravel/artisan", "start:sending", "kz"]

environment:
  APP_NAME: "Laravel"
  APP_ENV: "local"
  APP_KEY: "base64:nwSBuZ3DUWL/Jrw/bLF5BVJ9s6a/B5fQe/OomhJUCmo="
  APP_DEBUG: "true"
  APP_TIMEZONE: "UTC"
  APP_URL: "http://localhost:8084"

  FORWARD_REDIS_PORT: "6381"
  FORWARD_WEB_PORT: "8084"
  FORWARD_DB_PORT: "3308"

  APP_LOCALE: "en"
  APP_FALLBACK_LOCALE: 'en'
  APP_FAKER_LOCALE: "en_US"

  APP_MAINTENANCE_DRIVER: "file"
  APP_MAINTENANCE_STORE: "database"

  BCRYPT_ROUNDS: "12"

  LOG_CHANNEL: "stack"
  LOG_STACK: "single"
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: "debug"

  DB_CONNECTION: "pgsql"
  DB_HOST: "172.24.0.5"
  DB_PORT: "5432"
  DB_DATABASE: "agion-oros"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "root"

  SESSION_ENCRYPT: "false"
  SESSION_PATH: "/"
  SESSION_DOMAIN: "null"

  BROADCAST_CONNECTION: "log"
  CACHE_DRIVER: "file"
  QUEUE_CONNECTION: "sync"
  SESSION_DRIVER: "file"
  SESSION_LIFETIME: "120"

  REDIS_HOST: "redis"
  REDIS_PASSWORD: "null"
  REDIS_PORT: "6379"

  MAIL_MAILER: "log"
  MAIL_HOST: "127.0.0.1"
  MAIL_PORT: "2525"
  MAIL_USERNAME: "null"
  MAIL_PASSWORD: "null"
  MAIL_ENCRYPTION: "null"
  MAIL_FROM_ADDRESS: "hello@example.com"
  MAIL_FROM_NAME: "${APP_NAME}"

  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_BUCKET: ""
  AWS_USE_PATH_STYLE_ENDPOINT: "false"

  VITE_APP_NAME: "${APP_NAME}"

  OPENAI_API_KEY: ""
  OPENAI_ORGANIZATION: ""

  DEVELOPER_GATE_PASSWORD: staf