apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-fpm-metrics
  labels:
    type: fpm
spec:
  selector:
    app: {{ .Values.app }}-fpm
  ports:
    {{- .Values.fpm.metrics | toYaml | nindent 4 }}      