apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-web
spec:
  selector:
    app: {{ .Values.app }}-web
  ports:
    {{- .Values.web.service | toYaml | nindent 4 }}                               
  